# -*- coding: utf-8 -*-
"""Fraud_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g665V82zrfu2LTUWL5aLlmL_fXqGrKDH
"""

! pip install -q kaggle

! mkdir ~/.kaggle

! cp kaggle.json ~/.kaggle/

! chmod 600 ~/.kaggle/kaggle.json

! kaggle datasets list

! kaggle datasets download -d rupakroy/online-payments-fraud-detection-dataset

! unzip online-payments-fraud-detection-dataset.zip

import pandas as pd

df = pd.read_csv('PS_20174392719_1491204439457_log.csv')

df

df['type'].unique()

one_hot_encoded = pd.get_dummies(df['type'])

one_hot_encoded

df

df = df.drop('type', axis = 1)
df = df.join(one_hot_encoded)

df

df['nameDestType'] = df['nameDest'].str[0]
df

df = df.drop('nameDest', axis = 1)

one_hot_2 = pd.get_dummies(df['nameDestType'])
df = df.drop('nameDestType', axis = 1)
df = df.join(one_hot_2)
df

df = df.drop('nameOrig', axis = 1)

df

col_norm = ['amount', 'oldbalanceOrg', 'newbalanceOrig', 'oldbalanceDest', 'newbalanceDest']
for column in col_norm:
    df[column] = (df[column] - df[column].min()) / (df[column].max() - df[column].min())

df

df['isFraud'].sum()

df_isFraud = df[df['isFraud'] == 1]
df_isFraud

df_isnotFraud = df[df['isFraud'] == 0]
df_isnotFraud

df_isnotFraud = df_isnotFraud.sample(n = 8213)
df_isnotFraud

df = pd.concat([df_isFraud, df_isnotFraud])
df

X, y = df.drop('isFraud', axis = 1), df['isFraud']
X
y

X

y

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import accuracy_score, precision_score
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
print('Accuracy:', accuracy)
print('Precision:', precision)